name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            vcpkg/installed
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          vcpkgGitCommitId: 'b8a9371ae5a920b021132f443cc5658e82ac7551'
          runVcpkgInstall: true

      - name: Install vcpkg dependencies
        shell: pwsh
        run: |
          & "${env:GITHUB_WORKSPACE}/vcpkg/vcpkg" install
          Get-ChildItem -Path "${env:GITHUB_WORKSPACE}/vcpkg/installed" -Recurse

      - name: Debug vcpkg installation
        shell: pwsh
        run: |
          # Sprawdź, czy katalogi istnieją
          if (Test-Path "${env:GITHUB_WORKSPACE}/vcpkg/installed") {
            Write-Output "Directory vcpkg/installed exists."
            Get-ChildItem -Path "${env:GITHUB_WORKSPACE}/vcpkg/installed" -Recurse
          } else {
            Write-Output "Directory vcpkg/installed does not exist."
          }

      - name: Cache CMake files
        uses: actions/cache@v4
        with:
          path: |
            build/CMakeCache.txt
            build/CMakeFiles
          key: ${{ runner.os }}-cmake-cache-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-cmake-cache-

      - name: Install Ninja
        run: choco install ninja

      - name: Build project
        shell: pwsh
        run: |
          if (-not (Test-Path build)) { New-Item -ItemType Directory -Path build }
          Set-Location -Path build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="${env:GITHUB_WORKSPACE}/vcpkg/scripts/buildsystems/vcpkg.cmake" ..
          cmake --build .
          Get-ChildItem -Path build -Recurse
