name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cmake_generator: "Unix Makefiles"
          - os: windows-latest
            cmake_generator: "Visual Studio 16 2019"
          - os: macos-latest
            cmake_generator: "Xcode"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh  # Linux/MacOS
        .\vcpkg\bootstrap-vcpkg.bat  # Windows

    - name: Install dependencies
      run: |
        ./vcpkg/vcpkg install boost
        ./vcpkg/vcpkg install sqlite3
      if: runner.os != 'Windows'

    - name: Install dependencies on Windows
      run: |
        .\vcpkg\vcpkg install boost:x64-windows
        .\vcpkg\vcpkg install sqlite3:x64-windows
      if: runner.os == 'Windows'

    - name: Configure CMake
      run: cmake -S . -B build -G "${{ matrix.cmake_generator }}" -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build project
      run: cmake --build build --config Release

    - name: Package artifacts
      run: |
        zip -r app_with_deps_${{ matrix.os }}.zip build/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app_with_deps_${{ matrix.os }}
        path: app_with_deps_${{ matrix.os }}.zip
