name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout kodu wraz z submodułami (jeśli są)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2. Instalacja CMake (jeśli konieczne)
      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --version=3.25.0

      # 3. Cache vcpkg repo i zainstalowanych pakietów
      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            ${{ github.workspace }}/vcpkg/buildtrees
            ${{ github.workspace }}/vcpkg/packages
            ${{ github.workspace }}/vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      # 4. Instalacja vcpkg (jeśli nie jest w cache)
      - name: Install vcpkg
        if: ${{ ! steps.cache-vcpkg.outputs.cache-hit }}
        run: |
          git clone https://github.com/microsoft/vcpkg.git $env:GITHUB_WORKSPACE\vcpkg
          .\vcpkg\bootstrap-vcpkg.bat

      # 5. (Opcjonalnie) Aktualizacja vcpkg do najnowszej wersji
      - name: Update vcpkg
        if: ${{ steps.cache-vcpkg.outputs.cache-hit == 'true' }}
        run: |
          .\vcpkg\vcpkg.exe update
          .\vcpkg\vcpkg.exe upgrade --no-dry-run

      # 6. Dodanie vcpkg do PATH
      - name: Add vcpkg to PATH
        run: echo "${{ github.workspace }}/vcpkg" >> $env:GITHUB_PATH

      # 7. Instalacja zależności za pomocą vcpkg
      - name: Install dependencies with vcpkg
        run: |
          vcpkg install --triplet x64-windows

      # 8. Budowanie projektu
      - name: Build project
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 ^
            -DCMAKE_BUILD_TYPE=Debug ^
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" ^
            ..
          cmake --build . --config Debug

      # 9. (Opcjonalnie) Uruchomienie testów
      - name: Run Tests
        shell: cmd
        run: |
          cd build
          ctest --output-on-failure --build-config Debug
