name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Restore cache before vcpkg setup
      - name: Restore vcpkg cache
        uses: actions/cache@v3
        with:
          path: |
            vcpkg_installed
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-boost-sqlite
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install boost sqlite3
        shell: pwsh

      - name: Install Ninja
        run: |
          choco install ninja
        shell: pwsh

      - name: Configure CMake
        run: |
          if not exist build mkdir build
          cd build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ..
        shell: cmd

      # Save cache after successful vcpkg setup but before the build
      - name: Save vcpkg cache
        uses: actions/cache@v3
        with:
          path: |
            vcpkg_installed
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-boost-sqlite

      - name: Build
        run: |
          cd build
          cmake --build .
        shell: cmd

      - name: Run Tests
        run: |
          cd build
          ctest -C Debug --output-on-failure
        shell: cmd
