name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: microsoft/setup-vcpkg@v1
      with:
        vcpkgCommitId: a88ac64b8a0a9b43f4fd347fc32f3374a3700d52

    - name: Restore vcpkg cache
      uses: actions/cache@v4.0.2
      with:
        path: |
          vcpkg/installed
          vcpkg/downloads
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Install dependencies using vcpkg
      run: |
        vcpkg install
        vcpkg integrate install

    - name: Configure CMake
      run: |
        if not exist build mkdir build
        cd build
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ..

    - name: Build with Ninja
      run: |
        cd build
        cmake --build .

    - name: Save vcpkg cache
      uses: actions/cache@v4.0.2
      with:
        path: |
          vcpkg/installed
          vcpkg/downloads
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

    - name: Run tests
      run: |
        cd build
        ctest --verbose
