name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Przywróć cache przed instalacją vcpkg
      - name: Restore vcpkg cache
        uses: actions/cache@v3
        with:
          path: |
            vcpkg/installed
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-boost-sqlite
          restore-keys: |
            ${{ runner.os }}-vcpkg-boost-sqlite-
            ${{ runner.os }}-vcpkg-
          fail-on-cache-miss: false

      # Install Ninja build system
      - name: Install Ninja
        run: |
          echo "Installing Ninja..."
          choco install ninja
          echo "Ninja installed."

      # Set up vcpkg
      - name: Set up vcpkg
        run: |
          echo "Cloning vcpkg repository..."
          git clone https://github.com/microsoft/vcpkg.git
          echo "Bootstrapping vcpkg..."
          .\vcpkg\bootstrap-vcpkg.bat
          echo "Installing packages..."
          .\vcpkg\vcpkg install boost sqlite3
          echo "Vcpkg setup completed."

      # Save cache po instalacji vcpkg
      - name: Save vcpkg cache
        uses: actions/cache@v3
        with:
          path: |
            vcpkg/installed
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-boost-sqlite

      # Configure and build using CMake and Ninja
      - name: Configure CMake
        run: |
          if not exist build mkdir build
          cd build
          echo "Configuring CMake with Ninja..."
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ..
          echo "CMake configuration completed."
        shell: cmd

      - name: Build
        run: |
          cd build
          cmake --build .
        shell: cmd

      - name: Run Tests
        run: |
          cd build
          ctest -C Debug --output-on-failure
        shell: cmd
