name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up vcpkg
        run: |
          echo "Cloning vcpkg repository..."
          git clone https://github.com/microsoft/vcpkg.git
          echo "Bootstrapping vcpkg..."
          .\vcpkg\bootstrap-vcpkg.bat
          echo "Installing packages..."
          .\vcpkg\vcpkg install boost sqlite3
        shell: pwsh

      - name: Reinstall sqlite3 using vcpkg
        run: |
          echo "Reinstalling sqlite3..."
          .\vcpkg\vcpkg remove sqlite3
          .\vcpkg\vcpkg install sqlite3
        shell: pwsh

      - name: Check for sqlite3.h file
        run: |
          echo "Checking if sqlite3.h exists..."
          dir .\vcpkg\installed\x64-windows\include\sqlite3.h
        shell: pwsh

      - name: Install sqlite3 with core and tool features
        run: |
          echo "Installing sqlite3 with additional features..."
          .\vcpkg\vcpkg install sqlite3[core,tool]
        shell: pwsh

      - name: Install Visual Studio Build Tools
        run: |
          echo "Installing Visual Studio Build Tools..."
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --quiet --norestart"
        shell: pwsh

      - name: Configure CMake
        run: |
          echo "Creating build directory..."
          if (Test-Path build) {
            Remove-Item -Recurse -Force build
          }
          mkdir build
          cd build
          echo "Configuring CMake..."
          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ..
        shell: pwsh

      - name: Build
        run: |
          cd build
          echo "Building project..."
          cmake --build . --config Debug
        shell: pwsh

      - name: Run Tests
        run: |
          cd build
          echo "Running tests..."
          ctest -C Debug --output-on-failure
        shell: pwsh
