name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout kodu wraz z submodułami (jeśli są)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2. Instalacja CMake w wymaganej wersji
      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --version=3.29.2

      # 2a. Weryfikacja wersji CMake
      - name: Verify CMake version
        run: cmake --version

      # 3. Sprawdzenie obecności pliku vcpkg.json
      - name: List files in repository root
        run: dir "${{ github.workspace }}"

      # 4. Wyświetlenie zawartości pliku vcpkg.json
      - name: Display vcpkg.json content
        run: type "${{ github.workspace }}/vcpkg.json"

      # 5. Cache vcpkg repo i zainstalowanych pakietów
      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            ${{ github.workspace }}/vcpkg/buildtrees
            ${{ github.workspace }}/vcpkg/packages
            ${{ github.workspace }}/vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      # 6. Instalacja vcpkg (jeśli nie jest w cache)
      - name: Install vcpkg
        if: ${{ ! steps.cache-vcpkg.outputs.cache-hit }}
        run: |
          git clone https://github.com/microsoft/vcpkg.git %GITHUB_WORKSPACE%\vcpkg
          .\vcpkg\bootstrap-vcpkg.bat

      # 7. Weryfikacja instalacji vcpkg
      - name: Verify vcpkg installation
        run: |
          vcpkg version
          vcpkg list

      # 8. Dodanie vcpkg do PATH
      - name: Add vcpkg to PATH
        shell: pwsh
        run: |
          echo "${{ github.workspace }}/vcpkg" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # 9. Sprawdzenie PATH
      - name: Check PATH
        shell: pwsh
        run: echo $env:PATH

      # 10. Weryfikacja bieżącego katalogu przed instalacją
      - name: Verify current directory before install
        shell: cmd
        run: |
          echo "Current directory before install:"
          cd
          echo "Contents of current directory:"
          dir

      # 11. Instalacja zależności za pomocą vcpkg w trybie manifestu
      - name: Install dependencies with vcpkg
        shell: cmd
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          echo "Current directory for vcpkg install:"
          cd
          echo "Listing files before vcpkg install:"
          dir
          echo "Running vcpkg install with triplet x64-windows"
          vcpkg install --triplet x64-windows --debug || (
            echo "vcpkg install failed. Displaying log:"
            if exist "build\x64-Debug\vcpkg-manifest-install.log" (
              type "build\x64-Debug\vcpkg-manifest-install.log"
            ) else (
              echo "Log file not found."
            )
            exit /b 1
          )

      # 12. Weryfikacja zainstalowanych pakietów
      - name: List installed packages
        run: vcpkg list

      # 13. Budowanie projektu
      - name: Build project
        shell: cmd
        run: |
          mkdir build
          cd build
          echo "Running cmake with vcpkg toolchain"
          cmake -G "Visual Studio 17 2022" -A x64 ^
            -DCMAKE_BUILD_TYPE=Debug ^
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" ^
            ..
          echo "Building the project"
          cmake --build . --config Debug

      # 14. Listowanie zawartości katalogu build
      - name: List build directory
        run: dir build

      # 15. Listowanie zawartości katalogu vcpkg
      - name: List vcpkg directory
        run: dir "${{ github.workspace }}/vcpkg"

      # 16. (Opcjonalnie) Uruchomienie testów
      - name: Run Tests
        shell: cmd
        run: |
          cd build
          ctest --output-on-failure --build-config Debug

      # 17. Dodatkowe kroki debugowania po instalacji zależności
      - name: Additional Debugging Steps
        shell: cmd
        run: |
          echo "Additional debugging steps:"
          echo "Current directory:"
          cd
          echo "Listing vcpkg directory:"
          dir "%GITHUB_WORKSPACE%\vcpkg"
          echo "Listing build directory:"
          dir "%GITHUB_WORKSPACE%\build"
          echo "Verifying vcpkg manifest:"
          vcpkg manifest triplet
          echo "Running vcpkg install dry run:"
          vcpkg install --dry-run --triplet x64-windows
  
