name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install CMake (if necessary)
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --version=3.25.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}\vcpkg
          vcpkgGitCommitId: 'b8a9371ae5a920b021132f443cc5658e82ac7551'
          runVcpkgInstall: true
          doNotCache: false
          cleanAfterBuild: true

      - name: Build project
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 ^
            -DCMAKE_BUILD_TYPE=Debug ^
            -DCMAKE_TOOLCHAIN_FILE="%GITHUB_WORKSPACE%\vcpkg\scripts\buildsystems\vcpkg.cmake" ^
            ..
          cmake --build . --config Debug

      - name: Run Tests
        shell: cmd
        run: |
          cd build
          ctest --output-on-failure --configuration Debug
